#!/bin/bash
if [[ ! -d /Volumes/backup ]] ; then
    printf "Backup drive is not available. Exiting.\n"
    exit 1
fi

printf "Starting backup, please be patient.\n"

# rsync -av --delete -exclude=jeff/.Trash --exclude=.vscode --exclude="Library" \

rsync -av --delete -exclude=jeff/.Trash --exclude="Library" \
	/Users/jeff/ /Volumes/backup/jobs/ | tee ~/local/log/backup_momac.log
rc=$?

if [[ $rc -eq 0 ]] ; then
    printf "Backup completed successfully.\n"
    exit 0
else printf "Backup failed!\n"
    exit 1
fi

